/** Índice da central de ajuda. O conteúdo de cada página fica em `<slug>.html` nesta pasta. */

export type HelpPage = {
  slug: string;
  title: string;
  summary: string;
  keywords: string[];
};

export type HelpSection = { title: string; pages: HelpPage[] };

export const helpSections: HelpSection[] = [
  {
    title: "Comece por aqui",
    pages: [
      { slug: "visao-geral", title: "O que é o NoraCare", summary: "Apresenta o NoraCare para quem nunca usou: painel web da gestão e app do profissional, perfis, como a organização é montada (rede, local, setor, escala e plantão), os menus de cada lado e um guia de por onde começar por perfil.", keywords: ["o que é o NoraCare", "NoraCare", "painel web NoraCare", "app do profissional", "perfis de acesso", "por onde começar", "rede local setor escala", "menu do painel", "menu do app", "como funciona o NoraCare", "escalas e plantões"] },
      { slug: "primeiro-acesso", title: "Primeiro acesso e login", summary: "Como receber o convite por e-mail, criar sua senha, entrar, recuperar a senha esquecida, configurar a verificação em duas etapas, escolher o perfil e sair da conta.", keywords: ["primeiro acesso", "criar senha", "esqueci minha senha", "convite por e-mail", "link para criar senha", "como entrar no NoraCare", "recuperar senha", "verificação em duas etapas", "aplicativo autenticador", "trocar perfil", "como sair da conta", "link expirado"] },
      { slug: "app-no-celular", title: "App no celular: instalação, permissões e atualizações", summary: "Como baixar o NoraCare na App Store e na Google Play, usar pelo navegador, entender e revisar as permissões do celular e o que fazer na tela de atualização obrigatória.", keywords: ["instalar NoraCare celular", "baixar app NoraCare", "permissão de localização NoraCare", "localização o tempo todo", "check-in automático permissões", "atualização necessária NoraCare", "tela de atualização obrigatória", "alarmes e lembretes Android", "notificações NoraCare celular", "NoraCare no navegador", "bateria sem restrição app", "câmera biometria selfie"] },
      { slug: "perfis-e-acessos", title: "Perfis e níveis de acesso", summary: "Os perfis do NoraCare (master, gestor interno, coordenador, visualizador e profissional), o que cada um vê no menu e pode fazer, e como o acesso por rede, local, setor e escala é limitado.", keywords: ["perfis de acesso", "níveis de acesso", "perfil master", "gestor interno", "coordenador", "visualizador", "o que cada perfil vê", "quem pode convidar", "acesso por local e setor", "trocar de perfil"] },
    ],
  },
  {
    title: "Profissionais de saúde",
    pages: [
      { slug: "inicio-do-app", title: "Tela inicial e menu do app", summary: "O que aparece na tela Início do app do profissional (próximo plantão, semana, plantões anteriores, avisos de permissão e barra de plantão em curso), como usar o menu lateral, trocar de perfil e sair.", keywords: ["tela inicial do app", "menu do app", "próximo plantão", "esta semana plantões", "plantões anteriores", "barra de plantão em curso", "check-out pendente", "trocar perfil", "sair do app", "notificações sino", "permissões pendentes", "aparelho vinculado"] },
      { slug: "meus-plantoes", title: "Meus plantões", summary: "Como encontrar seus plantões na lista (semana, calendário e período), o que significam os selos e o que dá para fazer no detalhe: trocar, anunciar, assumir e pedir revisão de horário.", keywords: ["meus plantões", "lista de plantões", "plantões da semana", "filtrar plantões por período", "calendário de plantões", "status do plantão", "plantão sem check-out", "anunciar plantão", "trocar plantão", "assumir plantão", "pedir revisão de horário", "valor a confirmar plantão"] },
      { slug: "escalas-do-profissional", title: "Escalas", summary: "Como ver os plantões das escalas em que você participa: faixa de dias, calendário do mês, lista por escala e o que significa cada linha.", keywords: ["escalas", "ver escalas", "minhas escalas", "escala de plantões", "plantões dos colegas", "calendário de plantões", "semana de plantões", "plantão a definir", "substituição de plantão", "equipe da escala", "escalas que eu participo"] },
      { slug: "check-in-e-check-out", title: "Check-in e check-out", summary: "Como fazer check-in e check-out no app do profissional: quando o botão aparece, a confirmação de localização, a selfie quando a escala exige, o histórico do mês e as mensagens de erro mais comuns.", keywords: ["check-in", "check-out", "fazer check-in", "registrar ponto", "localização no check-in", "check-in sem internet", "histórico de check-in", "fora do raio", "check-out pendente", "selfie no check-in", "Check-in / out", "revisar horário"] },
      { slug: "check-in-automatico", title: "Check-in automático", summary: "Explica o check-in automático do profissional: quando está disponível (habilitado pela instituição), permissões e bateria do celular, como conferir se está pronto, os avisos do app e como resolver problemas.", keywords: ["check-in automático", "check-in passivo", "check-out automático", "registro automático do plantão", "permissão de localização", "localização o tempo todo", "bateria sem restrição", "atualização em segundo plano iPhone", "alarmes e lembretes Android", "check-in não registrou", "permissões pendentes", "aviso check-out pendente"] },
      { slug: "revisao-de-horario", title: "Pedir revisão de horário", summary: "Como pedir revisão de permanência de um plantão para corrigir a chegada ou a saída, o que informar no formulário, como acompanhar o pedido e o que muda quando a coordenação analisa.", keywords: ["revisão de horário", "revisão de permanência", "pedir revisão de ponto", "corrigir horário de entrada e saída", "esqueci o check-out", "check-out atrasado", "horário aprovado", "plantão em análise", "horário errado no plantão", "pedido de correção de ponto"] },
      { slug: "oportunidades", title: "Oportunidades: plantões anunciados", summary: "Como ver, buscar, filtrar e assumir plantões anunciados, e como funciona a candidatura quando a coordenação precisa aprovar.", keywords: ["oportunidades", "plantões anunciados", "assumir plantão", "candidatura plantão", "aprovação da coordenação", "plantão disponível", "pegar plantão", "filtrar plantões", "conflito de horário plantão", "cancelar candidatura", "cancelar anúncio de plantão", "plantões abertos"] },
      { slug: "trocas-e-passagens", title: "Trocas e passagens de plantão", summary: "Como pedir, aceitar ou recusar trocas e passagens de plantão, quando a coordenação precisa aprovar e como acompanhar o status de cada pedido.", keywords: ["trocar plantão", "passar plantão", "passagem de plantão", "troca de plantão", "aceitar troca de plantão", "recusar troca de plantão", "desistir da troca", "plantão de contrapartida", "aprovação da coordenação na troca", "status da troca de plantão"] },
      { slug: "extratos-e-remuneracao", title: "Extratos e remuneração", summary: "Como ler a tela Extratos do app do profissional: escolher o período, entender o resumo (saldo bruto, custos, adiantamentos e saldo líquido), valores fixos e por hora, plantões já pagos, bonificações, ajustes, nota fiscal e o demonstrativo para sócios.", keywords: ["extrato", "extrato de plantões", "quanto vou receber", "remuneração", "valor fixo mensal", "saldo líquido", "adiantamentos", "bonificação", "ajustes mensais", "nota fiscal", "plantão não realizado", "filtrar por período"] },
      { slug: "notificacoes-do-app", title: "Notificações no app", summary: "Central de Notificações do app para profissionais: quais avisos chegam, como marcar como lidos, para onde cada toque leva e como permitir avisos no celular.", keywords: ["notificações no app", "central de notificações", "avisos no celular", "marcar como lida", "notificação de troca", "plantão disponível", "permitir notificações", "sino de notificações", "não recebi notificação", "lembrete de check-in"] },
      { slug: "perfil-e-preferencias", title: "Perfil, preferências e sugestões", summary: "Perfil, preferências e sugestões do profissional: o que você edita e o que a instituição mantém, check-in automático, sugestões anônimas ou identificadas e como pedir a exclusão da conta.", keywords: ["perfil do profissional", "editar telefone no app", "trocar foto do perfil", "cadastrar biometria", "preferências de notificação", "check-in automático ligar", "permissão de localização check-in", "enviar sugestão anônima", "excluir minha conta", "conta bancária do profissional", "sair da conta", "alterar email no perfil"] },
    ],
  },
  {
    title: "Gestão: painel web",
    pages: [
      { slug: "dashboard", title: "Dashboard", summary: "Painel inicial da gestão: cartões de números, filtro de escalas, plantões em aberto nas próximas 72 horas, conflitos de horário e plantões anunciados.", keywords: ["dashboard", "painel administrativo", "plantões em aberto", "próximas 72 horas", "plantões em conflito", "conflito de horário", "plantões anunciados", "revisões de permanência pendentes", "filtro de escalas", "plantões hoje", "sem conflitos", "alocados vazios disponíveis"] },
      { slug: "escalas-visualizacoes", title: "Escalas: mensal, semanal e lista", summary: "Como usar as visões Mensal, Semanal e Lista da área Escalas: filtros por Rede, Local, Setor e Escala, cores e status dos plantões, navegação por período e ações em cada visão.", keywords: ["escalas mensal", "escalas semanal", "lista de plantões", "filtrar escalas por rede local setor", "cores dos plantões", "legenda de plantões", "conflito de plantão", "mês em rascunho", "publicar mês escala", "replicar semana", "check-in e check-out na lista", "trocar visão escalas celular"] },
      { slug: "criar-plantoes", title: "Criar e editar plantões", summary: "Como criar, editar e excluir plantões no painel web: escolher escala, horário e profissionais, entender os valores, repetir em vários dias, copiar uma semana ou um mês e lidar com anúncios e conflitos de horário.", keywords: ["criar plantão", "editar plantão", "adicionar plantão na escala", "recorrência de plantões", "copiar semana escala", "replicar semana", "replicar mês", "conflito de horário plantão", "excluir plantão", "atribuir profissional ao plantão", "remover profissional do plantão", "plantão anunciado"] },
      { slug: "configurar-escala", title: "Configuração, histórico e justificativas da escala", summary: "Opções da escala (ativo, equipe, pagamento, check-in, publicação e visibilidade), inativação e exclusão, histórico de trocas e de alterações, e justificativas de revisão de horário.", keywords: ["configurar escala", "editar escala", "publicar mês", "histórico de trocas", "justificativa revisão de horário", "check-in biométrico", "check-in passivo", "inativar escala", "janela de visibilidade", "dia de corte competência", "auditoria alterações escala", "revisão de permanência"] },
      { slug: "anuncios-e-aprovacoes", title: "Anúncios, trocas e aprovações", summary: "Como anunciar um plantão em aberto, ampliar o anúncio para outras escalas e aprovar ou recusar candidaturas, passagens e trocas na tela Aprovações.", keywords: ["anunciar plantão", "plantão anunciado", "plantão em aberto", "ampliar anúncio escalas", "aprovações candidatura", "aprovar candidatura plantão", "reprovar candidatura", "aprovar troca de plantão", "passagem de plantão", "desativar anúncio", "anúncio para rede", "candidatura a plantão coordenador"] },
      { slug: "registros-de-presenca", title: "Registros de presença e revisões de ponto", summary: "Como o gestor acompanha entradas e saídas, filtra registros, decide pedidos de revisão de horário, corrige horários manualmente e confere o histórico e os fechamentos automáticos.", keywords: ["revisão de ponto", "revisão de permanência", "registros de presença", "pedido de revisão de horário", "aprovar revisão de horário", "editar horário de check-in", "ajuste manual de horários", "check-out automático", "fechado automático revisar", "histórico de alterações"] },
      { slug: "profissionais", title: "Cadastro de profissionais", summary: "Lista e busca de profissionais, convite com campos obrigatórios e reenvio, ficha com dados, escalas vinculadas, edição e inativação, para a gestão no painel web.", keywords: ["cadastro de profissionais", "convidar profissional", "reenviar convite", "resetar senha profissional", "inativar profissional", "reativar profissional", "excluir profissional", "ficha do profissional", "escalas vinculadas profissional", "campos obrigatórios convite", "buscar profissional na lista", "editar cadastro do profissional"] },
      { slug: "equipe-de-gestao", title: "Gestores, coordenadores, visualizadores e masters", summary: "Como convidar, ver, editar, resetar senha, inativar, reativar e excluir masters, gestores internos, coordenadores e visualizadores, e o que cada perfil pode fazer.", keywords: ["convidar gestor interno", "convidar coordenador", "convidar visualizador", "adicionar master", "inativar usuário", "reativar usuário", "excluir usuário", "restaurar usuário", "resetar senha", "reenviar convite", "escopo de acesso visualizador", "quem pode convidar"] },
      { slug: "locais-e-empresas", title: "Locais, empresas e permissões globais", summary: "Como montar redes, locais e setores (com endereço e área do check-in), inativar, reativar ou excluir, cadastrar e manter empresas e entender quem pode ver e alterar cada parte.", keywords: ["cadastrar local", "nova rede", "endereço do check-in", "raio de alcance", "inativar local", "reativar setor", "excluir permanentemente", "cadastrar empresa", "empresa interna ou externa", "fonte pagadora", "importar empresas CSV", "CNPJ já cadastrado"] },
      { slug: "precificacao-e-regras", title: "Precificação, regras de pagamento, bonificações e ajustes", summary: "Como definir a grade de valores por hora ou o valor fixo de cada escala, as regras gerais para sócios de empresa interna, as bonificações e os ajustes mensais, e como cada item aparece para o profissional.", keywords: ["precificação", "valor por hora", "grade de valores", "valor fixo mensal", "bonificação", "ajustes mensais", "adicional ou desconto", "regras gerais", "INSS sócio", "valor de corte", "copiar mês anterior", "considerar realizado"] },
      { slug: "fechamento", title: "Fechamento mensal: importação, conciliação e pagamento", summary: "Passo a passo do fechamento mensal no painel web: importar os relatórios do Pega Plantão, conferir pendências e cadastros não encontrados, importar os plantões válidos em lote e exportar os pagamentos do mês.", keywords: ["fechamento mensal", "importar Pega Plantão", "conciliação do fechamento", "planilha pré-fechada", "histórico de importações", "remover lote", "exportar pagamentos", "fonte pagadora", "nota fiscal terceirizado", "profissional não encontrado na importação", "remessa bancária", "pendências da importação"] },
      { slug: "relatorios", title: "Relatórios", summary: "Lista os dez relatórios do painel (Apuração, Por Médico, Financeiro, Plantões, Escalas e outros), quem vê cada um, os filtros, a exportação para Excel e qual usar para cada pergunta.", keywords: ["relatórios", "relatório financeiro", "exportar excel", "exportar planilha relatório", "relatório de plantões", "apuração de pagamentos", "relatório por médico", "financeiro consolidado", "dados bancários relatório", "configurações das escalas", "filtrar relatório por período", "quem vê relatórios"] },
      { slug: "auditoria-e-notificacoes", title: "Auditoria e notificações do painel", summary: "Pesquisa no histórico de auditoria do painel (quem, o quê e quando), restauração de itens desativados e central de notificações da gestão: tipos, leitura e contestações de alocação.", keywords: ["auditoria", "histórico de alterações do painel", "quem fez a alteração", "pesquisar auditoria", "filtro de auditoria por ID", "restaurar rede local setor escala", "notificações do painel", "tipos de notificação gestão", "marcar notificação como lida", "contestação de alocação", "alocado incorretamente plantão", "nova candidatura aprovações"] },
    ],
  },
  {
    title: "Ajuda",
    pages: [
      { slug: "perguntas-frequentes", title: "Perguntas frequentes", summary: "32 perguntas e respostas curtas sobre acesso e senha, app, check-in, revisão de horário, trocas, valores, convites, publicação de escalas e fechamento, cada uma com link para a página que detalha.", keywords: ["perguntas frequentes NoraCare", "NoraCare não consigo fazer check-in", "NoraCare não recebi convite", "NoraCare esqueci a senha", "NoraCare app pede atualização", "check-in automático não registrou", "extrato valor diferente NoraCare", "NoraCare não vejo escala", "pedir revisão de horário NoraCare", "NoraCare como convidar profissional"] },
      { slug: "glossario", title: "Glossário", summary: "Glossário em ordem alfabética dos termos do app e do painel (plantão, escala, troca, passagem, anúncio, oportunidade, check-in automático, revisão de horário, fechamento, conciliação, competência, bonificação, ajuste mensal), cada um com link para a página que explica o assunto.", keywords: ["glossário NoraCare", "o que é plantão", "diferença entre troca e passagem", "o que é escala", "o que é competência financeira", "o que é conciliação do fechamento", "o que é bonificação", "o que significa ajuste mensal", "o que é oportunidade de plantão", "o que é check-in automático", "o que é revisão de horário", "o que é anúncio de plantão"] },
    ],
  },
];

export const helpPages = helpSections.flatMap((section) =>
  section.pages.map((page) => ({ ...page, section: section.title })),
);
